### ISSUE TITLE
Municipality model should use TranslatableManager

### ISSUE THREAD

**Issue by tuomas777** [City-of-Helsinki/django-munigeo#27]
Municipality is a translated model so it should use django-parler's TranslatableManager, but it doesn't. Because of that at least `Municipality.objects.get_or_create(...)` does not work atm.

**Comment by juyrjola** [comment]
Should be fixed in https://github.com/City-of-Helsinki/django-munigeo/commit/bffb1cb7cec1f1a825af9a77161f97b912af6464.
